education_system/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('verify_email/<uidb64>/<token>', authapp.verify_email, name='verify_email'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.profile, name='profile'),
]

education_system/education_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('chat/', include('chatapp.urls', namespace='chat')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education_system/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.db import models

class UserProfileManager(BaseUserManager):
    """Custom manager where email is the unique identifier for authentication."""

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular user with the given email and password."""
        if not email:
            raise ValueError(_('The Email field must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """Create and save a superuser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(email, password, **extra_fields)


class UserProfile(AbstractUser):
    class Role(models.IntegerChoices):
        ADMIN = 0, _('Administrator')
        TEACHER = 1, _('Teacher')
        STUDENT = 2, _('Student')

    username = None  # Отключаем использование username
    email = models.EmailField(_("email address"), unique=True)
    email_verify = models.BooleanField(_("email verify"), default=False)
    role = models.IntegerField(verbose_name=_("Role"), choices=Role.choices, default=Role.STUDENT)
    telegram = models.CharField(verbose_name=_("Telegram"), max_length=128, blank=True)
    avatar = models.ImageField(verbose_name=_("Avatar"), upload_to='avatar/', blank=True, default='avatar/default.png')

    USERNAME_FIELD = 'email'  # Определяем email как основной для входа
    REQUIRED_FIELDS = []  # Убираем обязательное поле username

    objects = UserProfileManager()  # Связываем с кастомным менеджером


    def __str__(self):
        return f'{self.email}'  # Используем email для отображения

    def set_active(self, is_active=True):
        self.is_active = is_active
        self.save()

    def restore(self):
        self.set_active(True)

    def delete(self, using=None, keep_parents=False):
        self.set_active(False)

education_system/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import UserProfile
import django.forms as forms
from django.utils.translation import gettext_lazy as _


class BaseFormMixin:
    """Mixin для общих настроек форм."""
    def add_class_to_fields(self, class_name):
        for name, field in self.fields.items():
            field.widget.attrs['class'] = class_name
            if 'help_text' in field.__dict__:
                field.help_text = f'Введите {_(name)}'


class LoginForm(AuthenticationForm, BaseFormMixin):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('username')  # Убираем поле username
        self.add_class_to_fields("login__form__{name}")

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if email and password:
            # Здесь используется email для аутентификации
            self.user_cache = UserProfile.objects.get(email=email)
            if self.user_cache.check_password(password):
                return cleaned_data
            else:
                raise forms.ValidationError(_("Invalid email or password."))

        raise forms.ValidationError(_("Please enter both email and password."))



class RegisterForm(UserCreationForm, BaseFormMixin):
    class Meta:
        model = UserProfile
        fields = ('email', 'first_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_class_to_fields('register__form')


class ProfileForm(UserChangeForm, BaseFormMixin):
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'email', 'telegram', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_class_to_fields('profile__form__{name}')
        # Скрываем поле пароля
        if 'password' in self.fields:
            self.fields['password'].widget = forms.HiddenInput()

education_system/authapp/views.py
from django.urls import reverse
from django.contrib import messages, auth
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import render, redirect

import logging

from authapp.utility.verify_email import send_email_for_verify

from authapp.forms import LoginForm, RegisterForm, ProfileForm

from authapp.models import UserProfile

logger = logging.getLogger(__name__)

def verify_email(request, uidb64, token):
    try:
        # Декодируем uid пользователя
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserProfile.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, UserProfile.DoesNotExist):
        user = None
        logger.warning(f"Invalid UID or user not found for UID: {uidb64}")

    # Проверяем наличие пользователя и токен
    if user is not None and token_generator.check_token(user, token):
        if not user.email_verify:  # Проверяем, что email еще не подтвержден
            user.email_verify = True
            user.save()
            auth.login(request, user)
            messages.success(request, 'Ваш email был успешно подтвержден.')
            logger.info(f"User {user.email} successfully verified their email.")
        else:
            messages.info(request, 'Ваш email уже был подтвержден ранее.')
            logger.info(f"User {user.email} attempted to re-verify their email.")
        return redirect('auth:profile')
    else:
        messages.warning(request, 'Ваша ссылка на верификацию недействительна. Пожалуйста, запросите новую.')
        logger.warning(f"Invalid or expired verification link used by UID: {uidb64}")
        return redirect('auth:profile')


def login(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']  # Получаем email из формы
            password = form.cleaned_data['password']

            # Аутентифицируем пользователя с использованием email
            user = authenticate(request, email=email, password=password)

            if user is not None:
                if not user.is_active:
                    messages.error(request, "Ваш аккаунт деактивирован. Свяжитесь с поддержкой.")
                    logger.warning(f"Deactivated user {user.email} attempted to log in.")
                elif not user.email_verify:
                    messages.error(request, "Ваш аккаунт не верифицирован. Проверьте почту для подтверждения.")
                    logger.warning(f"Unverified user {user.email} attempted to log in.")
                else:
                    auth_login(request, user)
                    logger.info(f"User {user.email} successfully logged in.")
                    return redirect('auth:profile')
            else:
                messages.error(request, "Неправильный email или пароль.")
                logger.warning("Failed login attempt.")
        else:
            messages.error(request, "Форма содержит ошибки, пожалуйста, проверьте данные.")
    else:
        form = LoginForm()

    context = {
        "title": "Авторизация",
        "form": form
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return redirect('auth:login')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)  # Создаем объект пользователя, но пока не сохраняем его
            user.save()

            # Отправляем письмо для подтверждения email
            try:
                send_email_for_verify(request, user)
                messages.warning(request, 'Перейдите на почту и подтвердите регистрацию.')
                logger.info(f"Verification email sent to {user.email}")
            except Exception as e:
                logger.error(f"Error sending verification email: {e}")
                messages.error(request, 'Ошибка при отправке письма для подтверждения.')

            return redirect('auth:profile')
        else:
            messages.error(request, 'Введены неправильные данные. Пожалуйста, проверьте форму.')
            logger.warning('Form validation failed during registration.')
    else:
        form = RegisterForm()

    context = {
        'title': 'Регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)


@login_required
def profile(request):
    user = request.user
    if request.method == 'POST':
        # Обработка запроса на повторную отправку письма для верификации
        if "btn_send_verify_email" in request.POST:
            try:
                send_email_for_verify(request, user)
                messages.success(request, 'Вам на почту было отправлено письмо с подтверждением.')
                logger.info(f"Verification email sent to {user.email}")
            except Exception as e:
                messages.error(request, 'Ошибка при отправке письма для подтверждения.')
                logger.error(f"Failed to send verification email to {user.email}: {e}")
            return redirect('auth:profile')

        # Обработка изменения профиля
        email_old = user.email
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            email_new = form.cleaned_data["email"]
            try:
                # Проверка изменения email
                if email_new != email_old:
                    user.email_verify = False
                    form.save()  # Сохраняем изменения профиля
                    send_email_for_verify(request, user)  # Отправляем письмо при изменении email
                    messages.warning(request, 'Email был изменен. Проверьте почту для подтверждения.')
                    logger.info(f"User {user.username} changed email from {email_old} to {email_new}")
                else:
                    form.save()
                    messages.success(request, 'Ваш профиль успешно обновлен.')
                    logger.info(f"User {user.username} updated their profile.")
            except Exception as e:
                messages.error(request, 'Произошла ошибка при сохранении профиля.')
                logger.error(f"Error updating profile for {user.username}: {e}")
            return redirect('auth:profile')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме.')

    # Отображение профиля
    else:
        form = ProfileForm(instance=user)

    context = {
        "title": "Профиль",
        "form": form
    }

    return render(request, "authapp/profile.html", context)

education_system/authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}

<form action="" method="post">
    {% csrf_token %}
    <div class="section__login">
        <div class="login">
            <label for="id_email" class="login__form__label">Email</label>
            <input type="email" name="email" id="id_email" class="login__form" required>
        </div>
        <div class="password">
            <label for="id_password" class="login__form__label">Пароль</label>
            <input type="password" name="password" id="id_password" class="login__form" required>
        </div>
        <div class="login__submit">
            <button type="submit" class="login__form__submit">Войти</button>
        </div>
        <a href="{% url 'auth:register' %}" class="login__link__register">Зарегистрироваться</a>
    </div>
</form>

{% endblock %}

education_system/authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<form method="post" enctype="multipart/form-data" class="profile__form__main">
    <div class="section__profile">
        {% csrf_token %}
        <div class="section__profile__avatar">
            <label style="cursor:pointer;" for="id_avatar">
                <img src="{{ user.avatar.url }}" alt="avatar" class="profile__avatar">
                <input type="file" name="avatar" accept="image/*" class="profile__form__avatar" id="id_avatar">
                <input type="hidden" name="password" disabled="" id="id_password">
            </label>
            <button type="submit" class="profile__submit">Сменить аватар</button>
        </div>
        <div class="section__profile__info">
            <div class="block__profile__form">
                <label for="id" class="profile__form__label">Ваш id</label>
                <input type="text" disabled value="{{user.id}}" class="profile__form" name="id" id="id">
            </div>
            <div class="block__profile__form">
                <label for="id_first_name" class="profile__form__label">ФИО</label>
                <input type="text" value="{{user.first_name}}" class="profile__form" name="first_name"
                       id="id_first_name">
            </div>
            <input type="submit" value="Изменить" class="profile__submit">
        </div>
    </div>

    <div class="section__message">
        <div class="block_message">
            <img src="{% static 'img/message/telegram.png' %}" alt="Телеграм" class="message__image">
            <div class="message__input">
                <p> Ваш логин:
                    <a href="http://t.me/{{user.telegram}}" target="_blank" class="message__input__link">
                        {{ user.telegram }}
                    </a>
                </p>
                <a class="profile__toggle__telegram" href="#">
                    {% if user.telegram %}
                    Изменить
                    {% else %}
                    Привязать
                    {% endif %}
                </a>
                <div class="profile__toggle__input__telegram" style="display: none;">
                    <input type="text" value="{{user.telegram}}" name="telegram" id="id_telegram" class="profile__input__telegram">
                    <input type="submit" value="Сохранить" class="profile__input__message__submit">
                </div>
            </div>
        </div>
        <div class="block_message">
            <img src="{% static 'img/message/email.png' %}" alt="Почта" class="message__image">
            <div class="message__input">
                <p> Ваша почта:
                    <a href="mailto: {{user.email}}" target="_blank" class="message__input__link">
                        {{ user.email }}
                    </a>
                </p>
                {{form.errors.email.as_text}}
                <a class="profile__toggle__email" href="#">Изменить</a>
                <div class="profile__toggle__input__email" style="display: none;">
                    <input type="email" value="{{user.email}}" name="email" id="id_email" class="profile__input__email">
                    <input type="submit" value="Сохранить" class="profile__input__message__submit">
                </div>
                {% if user.email_verify == 0 %}
                <span class="span__send__verify__email">Вы не прошли верификацию</span>
                <button type="submit" name="btn_send_verify_email" class="btn__send__verify__email">Пройти верификацию
                </button>
                {% endif %}
            </div>
            {% if user.email %}
            {% endif %}
        </div>
    </div>
</form>


{% endblock %}

education_system/authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}

<form action="" method="post">
    {% csrf_token %}
    <div class="register">
        <div class="register__block__form">
            <label for="id_email" class="register__form__label">Адрес электронной почты</label>
            <input type="email" name="email" id="id_email" required class="register__form">
            <div class="register__input__error">{{ form.email.errors }}</div>
        </div>
        <div class="register__block__form">
            <label for="id_first_name" class="register__form__label">ФИО</label>
            <input type="text" name="first_name" id="id_first_name" required class="register__form">
            <div class="register__input__error">{{ form.first_name.errors }}</div>
        </div>
        <div class="register__block__form">
            <label for="id_password1" class="register__form__label">Пароль</label>
            <input type="password" name="password1" autocomplete="new-password" id="id_password1" required
                   class="register__form">
            <div class="register__input__error">{{ form.password1.errors }}</div>
            <div>{{ form.password1.help_text }}</div>
        </div>
        <div class="register__block__form">
            <label for="id_password2" class="register__form__label">Подтвердить пароль</label>
            <input type="password" name="password2" autocomplete="new-password" id="id_password2" required
                   class="register__form">
            <div class="register__input__error">{{ form.password2.errors }}</div>
        </div>
        <div class="register__block__form">
            <button type="submit" class="register__form__submit">Зарегистрироваться</button>
        </div>
    </div>
</form>

{% endblock %}

education_system/authapp/templates/authapp/verify_email.html
{% autoescape off %}

Hi {{ user.get_username }}
Пожалуйста перейди по ссылке что бы закончить регистрацию

http://{{ domain }}{% url 'auth:verify_email' uidb64=uid token=token %}

{% endautoescape %}