education_system/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('verify_email/<uidb64>/<token>', authapp.verify_email, name='verify_email'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.profile, name='profile'),
]

education_system/education_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('chat/', include('chatapp.urls', namespace='chat')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education_system/teacher/urls.py
from django.urls import path
import teacher.views as teacher

app_name = 'teacher'

urlpatterns = [
    path('course/', teacher.course_teacher, name="course_teacher"),
    path('course/<slug:slug>', teacher.course_detail, name="course_detail"),
    path('course/<slug:slug>/m-<int:pk>', teacher.module_teacher, name="module_teacher"),
    path('course/<slug:slug>/students', teacher.course_student_teacher, name="course_student_teacher"),
    path('course/<slug:slug>/f-<int:pk>', teacher.final_session_all, name='final_course_session_teacher'), # Финальное занятие курсов
    path('course/<slug:slug>/m-<int:module_id>/f-<int:pk>', teacher.final_session_all, name='final_module_session_teacher'),  # Финальное занятие модуля
    path('course/<slug:slug>/t-<int:pk>', teacher.test, name='testing_course_teacher'), # Тестирование курсов
    path('course/<slug:slug>/m-<int:module_id>/t-<int:pk>', teacher.test, name='testing_module_teacher'),  # Тестирование модуля
    path('course/<slug:slug>/m-<int:module_id>/s-<int:pk>', teacher.session, name='session_teacher'), #
    #
    path('create/course/', teacher.course_create, name="course_create"),
    #
    path('change/<slug:slug>', teacher.course_change, name="course_change"),
    path('change/<slug:slug>/m-<int:pk>', teacher.module_change, name="module_change"),
    path('change/<slug:slug>/m-<int:module_id>/s-<int:pk>/', teacher.session_change, name="session_change"),
    path('change/<slug:slug>/f-<int:pk>/', teacher.final_session_change, name="final_session_course_change"),
    path('change/<slug:slug>/m-<int:module_id>/f-<int:pk>/', teacher.final_session_change, name="final_session_module_change"),
    path('change/<slug:slug>/m-<int:module_id>/t-<int:pk>/', teacher.edit_test, name="edit_test"),
]

education_system/mainapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from authapp.models import UserProfile
from django.db.models import Avg
from django.utils import timezone


class BaseFinalSession(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Название"))
    task_condition = models.TextField(verbose_name=_("Условие задания"), blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))

    class Meta:
        abstract = True  # Делает класс абстрактным


class Course(models.Model):
    class Complexity(models.IntegerChoices):
        EASY = 0, _('Easy')
        MEDIUM = 1, _('Medium')
        DIFFICULT = 2, _('Difficult')

    class CourseStatus(models.TextChoices):
        PLANNED = 'PL', _('Запланирован')
        ACTIVE = 'AC', _('Активен')
        COMPLETED = 'CO', _('Завершен')
        CANCELLED = 'CA', _('Отменен')

    name = models.CharField(max_length=128, verbose_name=_("Название"))
    slug = models.SlugField(max_length=128, verbose_name=_("Название на английском"), unique=True)
    desc = models.TextField(verbose_name=_("Описание"))
    complexity = models.IntegerField(verbose_name=_("Уровень сложности"),
                                     choices=Complexity.choices, default=Complexity.EASY)
    images = models.ImageField(verbose_name=_("Изображение"), upload_to='course/images/',
                               default='course/images/default.png')
    teacher = models.ForeignKey(UserProfile, verbose_name=_("Преподаватель"),
                                on_delete=models.CASCADE, related_name='courses_teacher')
    students = models.ManyToManyField(UserProfile, verbose_name=_("Студенты"),
                                      related_name='courses', related_query_name="course_students", blank=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата создания"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Дата обновления"))
    start_date = models.DateTimeField(verbose_name=_("Дата начала"), null=True, blank=True)
    end_date = models.DateTimeField(verbose_name=_("Дата окончания"), null=True, blank=True)
    status = models.CharField(max_length=2, choices=CourseStatus.choices, default=CourseStatus.ACTIVE)

    class Meta:
        ordering = ["name"]
        verbose_name = _("Курс")
        verbose_name_plural = _("Курсы")

    def __str__(self):
        return self.name

    def get_student_count(self):
        return self.students.count()

    def average_rating(self):
        if self.reviews.count() == 0:
            return None
        return self.reviews.aggregate(Avg('rating'))['rating__avg']


class Review(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='reviews')
    student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(verbose_name=_("Рейтинг"), choices=[(i, str(i)) for i in range(1, 6)])
    comment = models.TextField(verbose_name=_("Комментарий"), blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Отзыв")
        verbose_name_plural = _("Отзывы")

    def __str__(self):
        return f'Отзыв для {self.course.name} от {self.student.email}'


class Module(models.Model):
    STATUS_CHOICES = (
        ('active', _('Active')),
        ('completed', _('Completed')),
        ('canceled', _('Canceled')),
    )

    course = models.ForeignKey(
        Course,
        verbose_name='Курс',
        on_delete=models.CASCADE,
        related_name='module_course'
    )
    name = models.CharField(max_length=128, verbose_name="Название модуля")
    desc = models.TextField(verbose_name="Описание модуля", default='', blank=True, null=True)
    open = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Статус")
    position = models.PositiveIntegerField(verbose_name="Позиция модуля", default=0)
    completed_by = models.ManyToManyField(
        UserProfile,
        verbose_name="Пользователи, прошедшие модуль",
        related_name='completed_modules',
        blank=True
    )
    start_date = models.DateTimeField(verbose_name="Дата начала", null=True, blank=True)
    end_date = models.DateTimeField(verbose_name="Дата окончания", null=True, blank=True)

    class Meta:
        ordering = ["position"]
        verbose_name = "Модуль"
        verbose_name_plural = "Модули"

    def __str__(self):
        return self.name

    def is_active(self):
        """Проверяет, открыт ли модуль на текущий момент."""
        now = timezone.now()
        return self.open and (self.start_date is None or self.start_date <= now) and (
                self.end_date is None or self.end_date >= now)


class Session(models.Model):
    module = models.ForeignKey(
        Module,
        verbose_name=_("Модуль"),
        on_delete=models.CASCADE,
        related_name='sessions'
    )
    title = models.CharField(verbose_name=_("Название занятия"), max_length=200)  # Новое поле для названия занятия
    description = models.TextField(verbose_name=_("Описание занятия"), blank=True, null=True)  # Новое поле для описания
    homework_condition = models.TextField(verbose_name=_("Условие домашнего задания"), blank=True,
                                          null=True)  # Условие домашнего задания
    webinar_link = models.URLField(verbose_name=_("Ссылка на вебинар"), max_length=200, blank=True, null=True)
    presentation = models.FileField(verbose_name=_("Презентация"), upload_to='presentations/', blank=True, null=True)
    annotation = models.FileField(verbose_name=_("Аннотация"), upload_to='annotations/', blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))

    class Meta:
        verbose_name = _("Занятие")
        verbose_name_plural = _("Занятия")
        ordering = ["module"]

    def __str__(self):
        return f"{self.title} для модуля: {self.module.name}"


class Homework(models.Model):
    session = models.ForeignKey(
        Session,
        verbose_name=_("Занятие"),
        on_delete=models.CASCADE,
        related_name='homework_assignments'
    )
    answer = models.TextField(verbose_name=_("Ответ"), blank=True, null=True)
    submitted_by = models.ManyToManyField(
        UserProfile,
        verbose_name=_("Пользователи, сдавшие задание"),
        related_name='submitted_homework',
        blank=True
    )
    is_completed = models.BooleanField(default=False, verbose_name=_("Задание выполнено"))
    feedback = models.TextField(verbose_name=_("Обратная связь"), blank=True, null=True)

    class Meta:
        verbose_name = _("Домашнее задание")
        verbose_name_plural = _("Домашние задания")
        ordering = ["id"]

    def __str__(self):
        return f"для занятия: {self.session.module.name}"


class HomeworkFile(models.Model):
    homework = models.ForeignKey(
        Homework,
        verbose_name=_("Домашнее задание"),
        on_delete=models.CASCADE,
        related_name='files'
    )
    file = models.FileField(verbose_name=_("Файл с ответом"), upload_to='homework_submissions/')

    class Meta:
        verbose_name = _("Файл домашнего задания")
        verbose_name_plural = _("Файлы домашних заданий")

    def __str__(self):
        return f"Файл для задания: {self.homework.session.title}"


class FinalModuleSession(BaseFinalSession):
    module = models.ForeignKey(
        Module,
        verbose_name=_("Модуль"),
        on_delete=models.CASCADE,
        related_name='final_sessions'
    )

    class Meta:
        verbose_name = _("Финальное занятие модуля")
        verbose_name_plural = _("Финальные занятия модулей")

    def __str__(self):
        return self.title


class FinalCourseSession(BaseFinalSession):
    course = models.ForeignKey(
        Course,
        verbose_name=_("Курс"),
        on_delete=models.CASCADE,
        related_name='final_sessions'
    )

    class Meta:
        verbose_name = _("Финальное занятие курса")
        verbose_name_plural = _("Финальные занятия курсов")

    def __str__(self):
        return self.title


class FinalSessionResponse(models.Model):
    final_module_session = models.ForeignKey(
        FinalModuleSession,
        verbose_name=_("Финальное занятие модуля"),
        on_delete=models.CASCADE,
        related_name='responses',
        null=True,
        blank=True  # Позволяет пустое значение, если это задание курса
    )
    final_course_session = models.ForeignKey(
        FinalCourseSession,
        verbose_name=_("Финальное занятие курса"),
        on_delete=models.CASCADE,
        related_name='responses',
        null=True,
        blank=True  # Позволяет пустое значение, если это задание модуля
    )
    student = models.ForeignKey(
        UserProfile,
        verbose_name=_("Студент"),
        on_delete=models.CASCADE,
        related_name='final_responses'
    )
    comment = models.TextField(verbose_name=_("Комментарий студента"), blank=True, null=True)
    feedback = models.TextField(verbose_name=_("Комментарии преподавателя"), blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата отправки"))

    class Meta:
        verbose_name = _("Ответ на финальное занятие")
        verbose_name_plural = _("Ответы на финальные занятия")

    def __str__(self):
        if self.final_module_session:
            return f"Ответ студента {self.student} на занятие {self.final_module_session.title}"
        if self.final_course_session:
            return f"Ответ студента {self.student} на занятие {self.final_course_session.title}"
        return "Ответ студента без привязки к занятию"

education_system/teacher/models.py
from django.db import models

# Create your models here.

education_system/teacher/forms.py
from django import forms
from django.forms import inlineformset_factory

from mainapp.models import Course, Review, FinalCourseSession
from mainapp.models import Module, FinalModuleSession, FinalSessionResponse, FinalSessionFile
from mainapp.models import FinalSessionFile
from mainapp.models import Session, Homework, HomeworkFile
from mainapp.models import Test, TestQuestion, TestResponse, TestAnswerChoice, UserAnswer


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = (
            'name',
            'slug',
            'desc',
            'complexity',
            'images',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = 'course_form'


class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = (
            'name',
            'desc',
            'open',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = 'module_form'


class SessionForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = (
            'title',
            'description',
            'homework_condition',
            'webinar_link',
            'presentation',
            'annotation',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = 'lesson_form'


class FinalModuleSessionForm(forms.ModelForm):
    class Meta:
        model = FinalModuleSession
        fields = (
            'title',
            'task_condition',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = 'final_session_form'


class FinalCourseSessionForm(forms.ModelForm):
    class Meta:
        model = FinalCourseSession
        fields = (
            'title',
            'task_condition',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = 'final_session_form'

class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['title', 'description', 'duration', 'passing_score', 'is_active']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название теста'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание теста'}),
            'duration': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Продолжительность', 'min': 1}),
            'passing_score': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Проходной балл', 'min': 1}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class TestQuestionForm(forms.ModelForm):
    class Meta:
        model = TestQuestion
        fields = ['question_text', 'question_type']
        widgets = {
            'question_text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Текст вопроса'}),
            'question_type': forms.Select(attrs={'class': 'form-control'}),
        }

class TestAnswerChoiceForm(forms.ModelForm):
    class Meta:
        model = TestAnswerChoice
        fields = ['choice_text', 'is_correct']
        widgets = {
            'choice_text': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Вариант ответа'}),
            'is_correct': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def clean(self):
        super().clean()
        is_correct = self.cleaned_data.get('is_correct')
        question = self.instance.question

        if question.question_type == TestQuestion.SINGLE_CHOICE and is_correct:
            if question.choices.filter(is_correct=True).exclude(id=self.instance.id).exists():
                raise forms.ValidationError(_("Для вопросов с одним вариантом ответа может быть только один правильный ответ."))


QuestionFormSet = inlineformset_factory(Test, TestQuestion, form=TestQuestionForm, extra=0, can_delete=True)
AnswerChoiceFormSet = inlineformset_factory(TestQuestion, TestAnswerChoice, form=TestAnswerChoiceForm, extra=0, can_delete=True)


class TestFullForm(forms.Form):
    test_form = TestForm(prefix='test')
    question_formset = QuestionFormSet(prefix='questions')
    answer_choice_formset = AnswerChoiceFormSet(prefix='answers')

education_system/teacher/templates/teacher/course_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div>
    <div class="dropdown">
        <button onclick="myFunction()" class="dropbtn">Создать</button>
        <div id="myDropdown" class="dropdown-content">
          <a href="">Модуль</a>
          <a href="">Контрольное занятие</a>
          <a href="">Тестирование</a>
        </div>
      </div> 
</div>
<div class="course__detail__teacher">
    {% for module in modules %}
    <div class="course__detail__teacher__link">
        <p class="course__detail__teacher__link__name">
            {{module.name}}
            <img class="course__purchased__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
        </p>
        <div class="course__detail__teacher__crud">
            <a href="{% url 'teacher:module_teacher' module.course.slug module.id %}" class="course__detail__teacher__crud__desc">
                Подробнее
            </a>
            <a href="{% url 'teacher:module_change' module.course.slug module.id %}" class="course__detail__teacher__crud__change">
                Изменить
            </a>
        </div>
    </div>
    {% endfor %}
    {% for assignment in final_course_assignments %}
    <div class="course__detail__teacher__link">
        <p class="course__detail__teacher__link__name">
            {{assignment.title}}
            <img class="course__purchased__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
        </p>
        <div class="course__detail__teacher__crud">
            <a href="{% url 'teacher:final_course_session_teacher' assignment.course.slug assignment.id %}" class="course__detail__teacher__crud__desc">
                Подробнее
            </a>
            <a href="{% url 'teacher:final_session_course_change' assignment.course.slug assignment.id %}" class="course__detail__teacher__crud__change">
                Изменить
            </a>
        </div>
    </div>
    {% endfor %}
    {% for test in tests %}
    <div class="course__detail__teacher__link">
        <p class="course__detail__teacher__link__name">
            {{test.title}}
            <img class="course__purchased__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
        </p>
        <div class="course__detail__teacher__crud">
            <a href="{% url 'teacher:testing_course_teacher' test.course.slug test.id %}" class="course__detail__teacher__crud__desc">
                Подробнее
            </a>
            <a href="" class="course__detail__teacher__crud__change">
                Изменить
            </a>
        </div>
    </div>
    {% endfor %}
</div>
<div>
    <a href="{% url 'teacher:course_student_teacher' course.slug %}" class="course__detail__teacher__student">Участники курса</a>
</div>
{% endblock %}

education_system/teacher/templates/teacher/course_student_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<div class="lesson__teacher">
    <div class="student__teacher__items">
        <div>
            <p>№</p>
        </div>
        <div>
            <p>id</p>
        </div>
        <div>
            <p>ФИО</p>
        </div>
        <div>
            <p>
                Почта
            </p>
        </div>
        <div>
            <p>
                Телеграм
            </p>
        </div>
        <div>

        </div>
    </div>
    {% for item in course.students.all %}
    <div class="student__teacher__items">
        <div>
            <p class="lesson__teacher__items__text"></p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.id}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.first_name}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.email}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">
                {{item.telegram}}
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

education_system/teacher/templates/teacher/course_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<div>
    <div class="dropdown">
          <a href="{% url 'teacher:course_create' %}" class="dropbtn">Создать курс</a>
      </div> 
</div>
<div class="course">
	{% if courses %}
	<div class="course__users">
		<h1 class="course__section__title">
			Мои курсы
		</h1>
		<div class="course__list">
			{% for course in courses %}
			<div class="course__items">
                <div class="course__items__div__title">
                    <img src="{{ course.images.url }}" class="course__items__images" alt="Изображение курса">
                    <div class="course__items__button">
                        <a href="{% url 'teacher:course_change' course.slug %}" class="course__items__change">Изменить</a>
                    </div>
                </div>
				<h2 class="course__items__name">{{ course.name }}</h2>
				<div class="course__items__block__complexity">
					<p class="course__items__complexity">
						{{ course.get_complexity_display }}
					</p>
				</div>
				<a href="{% url 'teacher:course_detail' course.slug %}" class="course__items__link">Перейти к курсу</a>
			</div>
			{% endfor %}
		</div>
	</div>
	{% endif %}
</div>
{% endblock %}

education_system/teacher/templates/teacher/final_session.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<div class="lesson__teacher">
    <div class="lesson__teacher__items">
        <div>
            <p>№</p>
        </div>
        <div>
            <p>id</p>
        </div>
        <div>
            <p>Email</p>
        </div>
        <div>
            <p>
                Файл
            </p>
        </div>
        <div>
            <p>
                Комментарий студента
            </p>
        </div>
        <div>

        </div>
    </div>
    {% for item in final_response %}
    <div class="lesson__teacher__items">
        <div>

        </div>
        <div>
            <p class="lesson__teacher__items__text">{{ item.student.id }}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{ item.student.email }}</p>
        </div>
        <div>
            {% if item.files.count > 0 %}
            <a href="?download_response_id={{ item.id }}" target="_blank">Скачать</a>
            {% endif %}
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{ item.comment }}</p>
        </div>
        <div>
            {% if item.feedback %}
            <p class="lesson__teacher__items__text">{{ item.feedback }}</p>
            {% else %}
            <a href="">Оставить комментарий</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

education_system/teacher/templates/teacher/lesson_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<div class="lesson__teacher">
    <div class="lesson__teacher__items">
        <div>
            <p>№</p>
        </div>
        <div>
            <p>id</p>
        </div>
        <div>
            <p>Псевдоним</p>
        </div>
        <div>
            <p>
                Файл
            </p>
        </div>
        <div>
            <p>
                Комментарий
            </p>
        </div>
        <div>

        </div>
    </div>
    {% for item in home_work %}
    <div class="lesson__teacher__items">
        <div>
            <p class="lesson__teacher__items__text"></p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">
                {% for user in item.submitted_by.all %}
                {{ user.id }}
                {% empty %}
                Нет отправителей.
                {% endfor %}
            </p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">
                {% for user in item.submitted_by.all %}
                {{ user.email }}
                {% empty %}
                Нет отправителей.
                {% endfor %}
            </p>
        </div>
        <div>
            {% if item.files.count > 0 %}
                <a href="?download_response_id={{ item.id }}" target="_blank">Скачать</a>
            {% endif %}
        </div>
        <div>
            <p class="lesson__teacher__items__text">
                {{item.answer}}
            </p>
        </div>
        <div>
            {% if item.comment_teacher %}
            <p class="lesson__teacher__items__text">
                {{item.comment_teacher}}
            </p>
            {% else %}
            <a href="">Оставить комментарий</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

education_system/teacher/templates/teacher/module_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<div>
    <div class="dropdown">
        <button onclick="myFunction()" class="dropbtn">Создать</button>
        <div id="myDropdown" class="dropdown-content">
          <a href="">Занятие</a>
          <a href="">Контрольное занятие</a>
          <a href="">Тестирование</a>
        </div>
      </div> 
</div>
<div class="teacher__module">
    {% for item in sessions %}
    <div class="teacher__module__item">
        <div class="teacher__module__item__name">
            {{ item.title }}
            <img class="teacher__module__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
        </div>
        <div class="teacher__module__item__crud">
            <a href="{% url 'teacher:session_teacher' item.module.course.slug item.module.id item.id %}" class="course__detail__teacher__crud__desc">
                Подробнее
            </a>
            <a href="{% url 'teacher:session_change' item.module.course.slug item.module.id item.id %}" class="course__detail__teacher__crud__change">
                Изменить
            </a>
        </div>
    </div>   
    {% endfor %}
    {% for item in final_assignments %}
    <div class="teacher__module__item">
        <div class="teacher__module__item__name">
            {{ item.title }}
            <img class="teacher__module__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
        </div>
        <div class="teacher__module__item__crud">
            <a href="{% url 'teacher:final_module_session_teacher' item.module.course.slug item.module.id item.id %}" class="course__detail__teacher__crud__desc">
                Подробнее
            </a>
            <a href="{% url 'teacher:final_session_module_change' item.module.course.slug item.module.id item.id %}" class="course__detail__teacher__crud__change">
                Изменить
            </a>
        </div>
    </div>   
    {% endfor %}
   {% for test in tests %}
    <div class="teacher__module__item">
        <div class="teacher__module__item__name">
            {{ test.title }}
            <img class="teacher__module__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
        </div>
        <div class="teacher__module__item__crud">
            <a href="{% url 'teacher:testing_module_teacher' test.module.course.slug test.module.id test.id %}" class="course__detail__teacher__crud__desc">
                Подробнее
            </a>
            <a href="{% url 'teacher:edit_test' test.module.course.slug test.module.id test.id %}" class="course__detail__teacher__crud__change">
                Изменить
            </a>
        </div>
    </div>   
    {% endfor %}
</div>
{% endblock %}

education_system/teacher/templates/teacher/testing_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load custom_filters %}
{% load static %}
<div class="lesson__teacher">
    <div class="lesson__teacher__items">
        <div>
            <p>№</p>
        </div>
        <div>
            <p>id</p>
        </div>
        <div>
            <p>Псевдоним</p>
        </div>
        <div>
            <p>
                Количество вопросов
            </p>
        </div>
        <div>
            <p>
                Правильные ответы
            </p>
        </div>
        <div>
            <p>
                Процент выполнения
            </p>
        </div>
    </div>
    {% for item in response %}
    <div class="lesson__teacher__items">
        <div>
            <p class="lesson__teacher__items__text"></p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.student.id}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.student.email}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{questions_count}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.score}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">
                {% with percentage=item.score|percentage:questions_count %}
                {% if percentage is not None %}
                {{ percentage|floatformat:2 }}%
                {% else %}
                Н/Д
                {% endif %}
                {% endwith %}
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}