education_system/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('verify_email/<uidb64>/<token>', authapp.verify_email, name='verify_email'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.profile, name='profile'),
]

education_system/education_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('chat/', include('chatapp.urls', namespace='chat')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education_system/teacher/urls.py
from django.urls import path
import teacher.views as teacher

app_name = 'teacher'

urlpatterns = [
    path('course/', teacher.course_teacher, name="course_teacher"),
    path('course/<slug:slug>', teacher.course_detail, name="course_detail"),
    path('course/<slug:slug>/m-<int:pk>', teacher.module_teacher, name="module_teacher"),
    path('course/<slug:slug>/students', teacher.course_student_teacher, name="course_student_teacher"),
    path('course/<slug:slug>/f-<int:pk>', teacher.final_session_all, name='final_course_session_teacher'), # Финальное занятие курсов
    path('course/<slug:slug>/m-<int:module_id>/f-<int:pk>', teacher.final_session_all, name='final_module_session_teacher'),  # Финальное занятие модуля
    path('course/<slug:slug>/t-<int:pk>', teacher.test, name='testing_course_teacher'), # Тестирование курсов
    path('course/<slug:slug>/m-<int:module_id>/t-<int:pk>', teacher.test, name='testing_module_teacher'),  # Тестирование модуля
    path('course/<slug:slug>/m-<int:module_id>/s-<int:pk>', teacher.session, name='session_teacher'), #
    #
    path('create/course/', teacher.course_create, name="course_create"),
    #
    path('change/<slug:slug>', teacher.course_change, name="course_change"),
    path('change/<slug:slug>/m-<int:pk>', teacher.module_change, name="module_change"),
    path('change/<slug:slug>/m-<int:module_id>/s-<int:pk>/', teacher.session_change, name="session_change"),
    path('change/<slug:slug>/f-<int:pk>/', teacher.final_session_change, name="final_session_course_change"),
    path('change/<slug:slug>/m-<int:module_id>/f-<int:pk>/', teacher.final_session_change, name="final_session_module_change"),
    path('change/<slug:slug>/m-<int:module_id>/t-<int:pk>/', teacher.edit_test, name="edit_test"),
]

education_system/chatapp/models.py
from authapp.models import UserProfile
from mainapp.models import Course
from django.db import models


class Room(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Курс")
    name = models.CharField(max_length=255, verbose_name="Название комнаты")
    slug = models.SlugField(unique=True, verbose_name="Название ссылки для комнаты")
    user = models.ManyToManyField(UserProfile,
                                  related_name='rooms',
                                  related_query_name="room",
                                  blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ["name"]
        verbose_name = "Комната"
        verbose_name_plural = "Комнаты"


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE, verbose_name="Комната")
    user = models.ForeignKey(UserProfile, related_name='messages', on_delete=models.CASCADE,
                             verbose_name="Пользователь")
    content = models.TextField(verbose_name="Текст сообщения")
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")

    def __str__(self):
        return f'{self.room.name}'

    class Meta:
        ordering = ('date_added',)
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

education_system/mainapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from authapp.models import UserProfile
from django.db.models import Avg
from django.utils import timezone


class BaseFinalSession(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Название"))
    task_condition = models.TextField(verbose_name=_("Условие задания"), blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))

    class Meta:
        abstract = True  # Делает класс абстрактным


class Course(models.Model):
    class Complexity(models.IntegerChoices):
        EASY = 0, _('Easy')
        MEDIUM = 1, _('Medium')
        DIFFICULT = 2, _('Difficult')

    class CourseStatus(models.TextChoices):
        PLANNED = 'PL', _('Запланирован')
        ACTIVE = 'AC', _('Активен')
        COMPLETED = 'CO', _('Завершен')
        CANCELLED = 'CA', _('Отменен')

    name = models.CharField(max_length=128, verbose_name=_("Название"))
    slug = models.SlugField(max_length=128, verbose_name=_("Название на английском"), unique=True)
    desc = models.TextField(verbose_name=_("Описание"))
    complexity = models.IntegerField(verbose_name=_("Уровень сложности"),
                                     choices=Complexity.choices, default=Complexity.EASY)
    images = models.ImageField(verbose_name=_("Изображение"), upload_to='course/images/',
                               default='course/images/default.png')
    teacher = models.ForeignKey(UserProfile, verbose_name=_("Преподаватель"),
                                on_delete=models.CASCADE, related_name='courses_teacher')
    students = models.ManyToManyField(UserProfile, verbose_name=_("Студенты"),
                                      related_name='courses', related_query_name="course_students", blank=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата создания"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Дата обновления"))
    start_date = models.DateTimeField(verbose_name=_("Дата начала"), null=True, blank=True)
    end_date = models.DateTimeField(verbose_name=_("Дата окончания"), null=True, blank=True)
    status = models.CharField(max_length=2, choices=CourseStatus.choices, default=CourseStatus.ACTIVE)

    class Meta:
        ordering = ["name"]
        verbose_name = _("Курс")
        verbose_name_plural = _("Курсы")

    def __str__(self):
        return self.name

    def get_student_count(self):
        return self.students.count()

    def average_rating(self):
        if self.reviews.count() == 0:
            return None
        return self.reviews.aggregate(Avg('rating'))['rating__avg']


class Review(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='reviews')
    student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(verbose_name=_("Рейтинг"), choices=[(i, str(i)) for i in range(1, 6)])
    comment = models.TextField(verbose_name=_("Комментарий"), blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Отзыв")
        verbose_name_plural = _("Отзывы")

    def __str__(self):
        return f'Отзыв для {self.course.name} от {self.student.email}'


class Module(models.Model):
    STATUS_CHOICES = (
        ('active', _('Active')),
        ('completed', _('Completed')),
        ('canceled', _('Canceled')),
    )

    course = models.ForeignKey(
        Course,
        verbose_name='Курс',
        on_delete=models.CASCADE,
        related_name='module_course'
    )
    name = models.CharField(max_length=128, verbose_name="Название модуля")
    desc = models.TextField(verbose_name="Описание модуля", default='', blank=True, null=True)
    open = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Статус")
    position = models.PositiveIntegerField(verbose_name="Позиция модуля", default=0)
    completed_by = models.ManyToManyField(
        UserProfile,
        verbose_name="Пользователи, прошедшие модуль",
        related_name='completed_modules',
        blank=True
    )
    start_date = models.DateTimeField(verbose_name="Дата начала", null=True, blank=True)
    end_date = models.DateTimeField(verbose_name="Дата окончания", null=True, blank=True)

    class Meta:
        ordering = ["position"]
        verbose_name = "Модуль"
        verbose_name_plural = "Модули"

    def __str__(self):
        return self.name

    def is_active(self):
        """Проверяет, открыт ли модуль на текущий момент."""
        now = timezone.now()
        return self.open and (self.start_date is None or self.start_date <= now) and (
                self.end_date is None or self.end_date >= now)


class Session(models.Model):
    module = models.ForeignKey(
        Module,
        verbose_name=_("Модуль"),
        on_delete=models.CASCADE,
        related_name='sessions'
    )
    title = models.CharField(verbose_name=_("Название занятия"), max_length=200)  # Новое поле для названия занятия
    description = models.TextField(verbose_name=_("Описание занятия"), blank=True, null=True)  # Новое поле для описания
    homework_condition = models.TextField(verbose_name=_("Условие домашнего задания"), blank=True,
                                          null=True)  # Условие домашнего задания
    webinar_link = models.URLField(verbose_name=_("Ссылка на вебинар"), max_length=200, blank=True, null=True)
    presentation = models.FileField(verbose_name=_("Презентация"), upload_to='presentations/', blank=True, null=True)
    annotation = models.FileField(verbose_name=_("Аннотация"), upload_to='annotations/', blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))

    class Meta:
        verbose_name = _("Занятие")
        verbose_name_plural = _("Занятия")
        ordering = ["module"]

    def __str__(self):
        return f"{self.title} для модуля: {self.module.name}"


class Homework(models.Model):
    session = models.ForeignKey(
        Session,
        verbose_name=_("Занятие"),
        on_delete=models.CASCADE,
        related_name='homework_assignments'
    )
    answer = models.TextField(verbose_name=_("Ответ"), blank=True, null=True)
    submitted_by = models.ManyToManyField(
        UserProfile,
        verbose_name=_("Пользователи, сдавшие задание"),
        related_name='submitted_homework',
        blank=True
    )
    is_completed = models.BooleanField(default=False, verbose_name=_("Задание выполнено"))
    feedback = models.TextField(verbose_name=_("Обратная связь"), blank=True, null=True)

    class Meta:
        verbose_name = _("Домашнее задание")
        verbose_name_plural = _("Домашние задания")
        ordering = ["id"]

    def __str__(self):
        return f"для занятия: {self.session.module.name}"


class HomeworkFile(models.Model):
    homework = models.ForeignKey(
        Homework,
        verbose_name=_("Домашнее задание"),
        on_delete=models.CASCADE,
        related_name='files'
    )
    file = models.FileField(verbose_name=_("Файл с ответом"), upload_to='homework_submissions/')

    class Meta:
        verbose_name = _("Файл домашнего задания")
        verbose_name_plural = _("Файлы домашних заданий")

    def __str__(self):
        return f"Файл для задания: {self.homework.session.title}"


class FinalModuleSession(BaseFinalSession):
    module = models.ForeignKey(
        Module,
        verbose_name=_("Модуль"),
        on_delete=models.CASCADE,
        related_name='final_sessions'
    )

    class Meta:
        verbose_name = _("Финальное занятие модуля")
        verbose_name_plural = _("Финальные занятия модулей")

    def __str__(self):
        return self.title


class FinalCourseSession(BaseFinalSession):
    course = models.ForeignKey(
        Course,
        verbose_name=_("Курс"),
        on_delete=models.CASCADE,
        related_name='final_sessions'
    )

    class Meta:
        verbose_name = _("Финальное занятие курса")
        verbose_name_plural = _("Финальные занятия курсов")

    def __str__(self):
        return self.title


class FinalSessionResponse(models.Model):
    final_module_session = models.ForeignKey(
        FinalModuleSession,
        verbose_name=_("Финальное занятие модуля"),
        on_delete=models.CASCADE,
        related_name='responses',
        null=True,
        blank=True  # Позволяет пустое значение, если это задание курса
    )
    final_course_session = models.ForeignKey(
        FinalCourseSession,
        verbose_name=_("Финальное занятие курса"),
        on_delete=models.CASCADE,
        related_name='responses',
        null=True,
        blank=True  # Позволяет пустое значение, если это задание модуля
    )
    student = models.ForeignKey(
        UserProfile,
        verbose_name=_("Студент"),
        on_delete=models.CASCADE,
        related_name='final_responses'
    )
    comment = models.TextField(verbose_name=_("Комментарий студента"), blank=True, null=True)
    feedback = models.TextField(verbose_name=_("Комментарии преподавателя"), blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата отправки"))

    class Meta:
        verbose_name = _("Ответ на финальное занятие")
        verbose_name_plural = _("Ответы на финальные занятия")

    def __str__(self):
        if self.final_module_session:
            return f"Ответ студента {self.student} на занятие {self.final_module_session.title}"
        if self.final_course_session:
            return f"Ответ студента {self.student} на занятие {self.final_course_session.title}"
        return "Ответ студента без привязки к занятию"

education_system/teacher/models.py
from django.db import models

# Create your models here.

education_system/teacher/templates/teacher/crud/change/course_change_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="course__change__form__image" style="cursor: pointer;">
        <label style="cursor:pointer;" for="id_images">
            {% if courses.images.url %}
            <img src="{{ courses.images.url }}" alt="image course" class="course_form_img">
            {% else %}
            <img src="{% static 'img/course/camera.png' %}" alt="image course" class="course_form_img">
            {% endif %}
            <input type="file" name="images" accept="image/*" class="course_form" id="id_images">
        </label>
    </div>
    <div class="course__change__form">
        <input type="text" name="name" value="{{courses.name}}" maxlength="128" class="course_form" required="" id="id_name">
    </div>
    <div class="course__change__form">
        <input type="text" name="slug" value="{{courses.slug}}" maxlength="128" class="course_form" required="" id="id_slug">
    </div>
    <div class="course__change__form">
        <textarea name="desc" cols="40" rows="10" class="course_form course_form_textarea" required="" id="id_desc">{{courses.desc}}</textarea>
    </div>
    <div class="course__change__form">
        {{form.complexity}}
    </div>
    <div class="course__change__form">
        <button type="submit" class="course_form">Изменить курс</button>
    </div>
</form>
{% endblock %}

education_system/teacher/templates/teacher/crud/change/final_event_change_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="module__change__form">
        <input type="text" name="title" value="{{final_session.title}}" maxlength="128" class="module_form" required="" id="id_title">
    </div>
    <div class="module__change__form">
        <input type="text" name="task_condition" value="{{final_session.task_condition}}" maxlength="128" class="module_form" required="" id="id_task_condition">
    </div>
    <div class="module__change__form">
        <button type="submit" class="module_form">Изменить модуль</button>
    </div>
</form>
{% endblock %}

education_system/teacher/templates/teacher/crud/change/lesson_change_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="lesson__change__form">
        <input type="text" name="title" value="{{session.title}}" maxlength="128" class="lesson_form" required="" id="id_title" placeholder="Название">
    </div>
    <div class="course__change__form">
        <textarea name="description" cols="40" rows="10" class="course_form course_form_textarea" required="" id="id_description" placeholder="Описание">{{session.description}}</textarea>
    </div>
    <div class="lesson__change__form">
        <input type="url" name="webinar_link" value="{{session.webinar_link}}" maxlength="200" class="lesson_form" id="id_webinar_link" placeholder="Ссылка на вебинар">
    </div>
    <div class="lesson__change__form lesson__change__form__file">
        <div class="lesson__change__form__file__item">
            <label for="id_presentation">Презентация:</label>
            {% if session.presentation %}
            <a href="{{session.presentation.url}}" target="_blank">{{session.presentation}}</a>
            {%endif%}
            <input type="file" name="presentation" accept="file/*" class="lesson_form" id="id_presentation">    
        </div>
        <div class="lesson__change__form__file__item">
            <label for="id_annotation">Анотация:</label>
            {% if session.annotation %}
            <a href="{{session.annotation.url}}" target="_blank">{{session.annotation}}</a>
            {%endif%}
            <input type="file" name="annotation" accept="file/*" class="lesson_form" id="id_annotation">
        </div>
    </div>
    <div class="course__change__form">
        <textarea name="homework_condition" cols="40" rows="10" class="course_form course_form_textarea" required="" id="id_homework_condition" placeholder="Домашняя работа">{{session.homework_condition}}</textarea>
    </div>
    <div class="lesson__change__form">
        <button type="submit" class="lesson_form">Изменить занятие</button>
    </div>
</form>
{% endblock %}

education_system/teacher/templates/teacher/crud/change/module_change_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="module__change__form">
        <input type="text" name="name" value="{{module.name}}" maxlength="128" class="module_form" required="" id="id_name">
    </div>
    <div class="module__change__form">
        <input type="text" name="desc" value="{{module.desc}}" maxlength="128" class="module_form" required="" id="id_desc">
    </div>
    <div class="module__change__form">
        <label for="id_open" class="custom-checkbox">
            {% if module.open == 1%}
            <input type="checkbox" name="open" class="module_form" id="id_open" checked>
            {% else %}
            <input type="checkbox" name="open" class="module_form" id="id_open">
            {% endif %}
            <span >Открытие модуля</span>
        </label> 
    </div>
    <div class="module__change__form">
        <button type="submit" class="module_form">Изменить модуль</button>
    </div>
</form>
{% endblock %}

education_system/teacher/templates/teacher/crud/change/testing_change_teacher.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <h2>{{ title }}</h2>
    <form method="post" id="test-form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.errors }}
        </div>
        <div class="form-group">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
        <div class="form-group">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
        <div class="form-group">
            {{ form.duration.label_tag }} {{ form.duration }}
        </div>
        <div class="form-group">
            {{ form.passing_score.label_tag }} {{ form.passing_score }}
        </div>
        <div class="form-group">
            {{ form.is_active.label_tag }} {{ form.is_active }}
        </div>

        <h3>Вопросы</h3>
        <div id="questions-container">
            {% for question_form, answer_formset in question_answer_pairs %}
            <div class="question-form" data-question-id="{{ forloop.counter0 }}">
                {{ question_form.errors }} <!-- Не забудьте отобразить идентификатор формы -->
                {{ question_form.as_p }} <!-- Не забудьте отобразить идентификатор формы -->

                <div class="answer-container">
                    {{ answer_formset.management_form }}  <!-- Скрытые поля управления для ответов -->
                    {% for answer_form in answer_formset %}
                    {{ answer_form.errors }}
                    <div class="answer-form">
                        {{ answer_form.as_p }}  <!-- Отображаем поля ответов -->
                        <button type="button" class="btn btn-danger remove-answer">Удалить ответ</button>
                    </div>
                    {% endfor %}
                </div>

                <button type="button" class="btn btn-success add-answer">Добавить ответ</button>
                <button type="button" class="btn btn-danger remove-question">Удалить вопрос</button>
                <!-- Кнопка удаления -->
            </div>
            {% endfor %}
        </div>


        <button type="button" id="add-question" class="btn btn-primary">Добавить вопрос</button>
        <button type="submit" class="btn btn-success">Сохранить тест</button>
    </form>
</div>

<template id="question-template">
    <div class="question-form" data-question-id="__prefix__">
        <p>
            <label for="id_questions-__prefix__-question_text">Текст вопроса:</label>
            <textarea name="questions-__prefix__-question_text" cols="40" rows="10" class="form-control"
                  placeholder="Введите текст вопроса"></textarea>
        </p>
        <p>
            <label for="id_questions-__prefix__-question_type">Тип вопроса:</label>
            <select name="questions-__prefix__-question_type" class="form-control">
            <option value="single">Один вариант ответа</option>
            <option value="multiple">Несколько вариантов ответов</option>
            <option value="text">Текстовый ответ</option>
        </select>
        </p>
        <div class="answer-container" data-answer-prefix="__prefix__"></div>
        <button type="button" class="btn btn-success add-answer">Добавить ответ</button>
        <button type="button" class="btn btn-danger remove-question">Удалить вопрос</button>
    </div>
</template>

<template id="answer-template">
    <div class="answer-form">
        <input type="text" name="answers-__prefix__-choice_text" class="form-control"
               placeholder="Введите вариант ответа">
        <label><input type="checkbox" name="answers-__prefix__-is_correct"> Правильный ответ</label>
        <button type="button" class="btn btn-danger remove-answer">Удалить ответ</button>
    </div>
</template>


{% endblock %}