education_system/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('verify_email/<uidb64>/<token>', authapp.verify_email, name='verify_email'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.profile, name='profile'),
]

education_system/education_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('chat/', include('chatapp.urls', namespace='chat')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education_system/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.course_list, name='course_list'), # Список курсов
    path('<slug:slug>/', mainapp.course_detail, name='course_detail'), # Детали курсов (не куплены)
    path('user/course/<slug:slug>/', mainapp.purchased_course_detail, name='purchased_course_detail'), # Детали курсов (куплены)
    path('user/course/<slug:slug>/m-<int:pk>/', mainapp.module_detail, name='module_detail'), # Модули
    path('user/course/<slug:slug>/m-<int:module_id>/l-<int:pk>', mainapp.session, name='session'), # Занятие
    path('user/course/<slug:slug>/f-<int:pk>', mainapp.final_session_all, name='final_course_session'), # Финальное занятие курсов
    path('user/course/<slug:slug>/m-<int:module_id>/f-<int:pk>', mainapp.final_session_all, name='final_module_session'), # Финальное занятие модуля
    path('user/course/<slug:slug>/t-<int:test_id>', mainapp.take_test, name='take_test_course'), # Тестирование курсов
    path('user/course/<slug:slug>/m-<int:module_id>/t-<int:test_id>', mainapp.take_test, name='take_test_module'), # Тестирование модуля
    path('user/course/result/test-<int:response_id>', mainapp.test_result, name='test_result'), # Тестирование результаты
]

education_system/mainapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from authapp.models import UserProfile
from django.db.models import Avg
from django.utils import timezone


class BaseFinalSession(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Название"))
    task_condition = models.TextField(verbose_name=_("Условие задания"), blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))

    class Meta:
        abstract = True  # Делает класс абстрактным


class Course(models.Model):
    class Complexity(models.IntegerChoices):
        EASY = 0, _('Easy')
        MEDIUM = 1, _('Medium')
        DIFFICULT = 2, _('Difficult')

    class CourseStatus(models.TextChoices):
        PLANNED = 'PL', _('Запланирован')
        ACTIVE = 'AC', _('Активен')
        COMPLETED = 'CO', _('Завершен')
        CANCELLED = 'CA', _('Отменен')

    name = models.CharField(max_length=128, verbose_name=_("Название"))
    slug = models.SlugField(max_length=128, verbose_name=_("Название на английском"), unique=True)
    desc = models.TextField(verbose_name=_("Описание"))
    complexity = models.IntegerField(verbose_name=_("Уровень сложности"),
                                     choices=Complexity.choices, default=Complexity.EASY)
    images = models.ImageField(verbose_name=_("Изображение"), upload_to='course/images/',
                               default='course/images/default.png')
    teacher = models.ForeignKey(UserProfile, verbose_name=_("Преподаватель"),
                                on_delete=models.CASCADE, related_name='courses_teacher')
    students = models.ManyToManyField(UserProfile, verbose_name=_("Студенты"),
                                      related_name='courses', related_query_name="course_students", blank=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата создания"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Дата обновления"))
    start_date = models.DateTimeField(verbose_name=_("Дата начала"), null=True, blank=True)
    end_date = models.DateTimeField(verbose_name=_("Дата окончания"), null=True, blank=True)
    status = models.CharField(max_length=2, choices=CourseStatus.choices, default=CourseStatus.ACTIVE)

    class Meta:
        ordering = ["name"]
        verbose_name = _("Курс")
        verbose_name_plural = _("Курсы")

    def __str__(self):
        return self.name

    def get_student_count(self):
        return self.students.count()

    def average_rating(self):
        if self.reviews.count() == 0:
            return None
        return self.reviews.aggregate(Avg('rating'))['rating__avg']


class Review(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='reviews')
    student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(verbose_name=_("Рейтинг"), choices=[(i, str(i)) for i in range(1, 6)])
    comment = models.TextField(verbose_name=_("Комментарий"), blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Отзыв")
        verbose_name_plural = _("Отзывы")

    def __str__(self):
        return f'Отзыв для {self.course.name} от {self.student.email}'


class Module(models.Model):
    STATUS_CHOICES = (
        ('active', _('Active')),
        ('completed', _('Completed')),
        ('canceled', _('Canceled')),
    )

    course = models.ForeignKey(
        Course,
        verbose_name='Курс',
        on_delete=models.CASCADE,
        related_name='module_course'
    )
    name = models.CharField(max_length=128, verbose_name="Название модуля")
    desc = models.TextField(verbose_name="Описание модуля", default='', blank=True, null=True)
    open = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Статус")
    position = models.PositiveIntegerField(verbose_name="Позиция модуля", default=0)
    completed_by = models.ManyToManyField(
        UserProfile,
        verbose_name="Пользователи, прошедшие модуль",
        related_name='completed_modules',
        blank=True
    )
    start_date = models.DateTimeField(verbose_name="Дата начала", null=True, blank=True)
    end_date = models.DateTimeField(verbose_name="Дата окончания", null=True, blank=True)

    class Meta:
        ordering = ["position"]
        verbose_name = "Модуль"
        verbose_name_plural = "Модули"

    def __str__(self):
        return self.name

    def is_active(self):
        """Проверяет, открыт ли модуль на текущий момент."""
        now = timezone.now()
        return self.open and (self.start_date is None or self.start_date <= now) and (
                self.end_date is None or self.end_date >= now)


class Session(models.Model):
    module = models.ForeignKey(
        Module,
        verbose_name=_("Модуль"),
        on_delete=models.CASCADE,
        related_name='sessions'
    )
    title = models.CharField(verbose_name=_("Название занятия"), max_length=200)  # Новое поле для названия занятия
    description = models.TextField(verbose_name=_("Описание занятия"), blank=True, null=True)  # Новое поле для описания
    homework_condition = models.TextField(verbose_name=_("Условие домашнего задания"), blank=True,
                                          null=True)  # Условие домашнего задания
    webinar_link = models.URLField(verbose_name=_("Ссылка на вебинар"), max_length=200, blank=True, null=True)
    presentation = models.FileField(verbose_name=_("Презентация"), upload_to='presentations/', blank=True, null=True)
    annotation = models.FileField(verbose_name=_("Аннотация"), upload_to='annotations/', blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name=_("Активность"))

    class Meta:
        verbose_name = _("Занятие")
        verbose_name_plural = _("Занятия")
        ordering = ["module"]

    def __str__(self):
        return f"{self.title} для модуля: {self.module.name}"


class Homework(models.Model):
    session = models.ForeignKey(
        Session,
        verbose_name=_("Занятие"),
        on_delete=models.CASCADE,
        related_name='homework_assignments'
    )
    answer = models.TextField(verbose_name=_("Ответ"), blank=True, null=True)
    submitted_by = models.ManyToManyField(
        UserProfile,
        verbose_name=_("Пользователи, сдавшие задание"),
        related_name='submitted_homework',
        blank=True
    )
    is_completed = models.BooleanField(default=False, verbose_name=_("Задание выполнено"))
    feedback = models.TextField(verbose_name=_("Обратная связь"), blank=True, null=True)

    class Meta:
        verbose_name = _("Домашнее задание")
        verbose_name_plural = _("Домашние задания")
        ordering = ["id"]

    def __str__(self):
        return f"для занятия: {self.session.module.name}"


class HomeworkFile(models.Model):
    homework = models.ForeignKey(
        Homework,
        verbose_name=_("Домашнее задание"),
        on_delete=models.CASCADE,
        related_name='files'
    )
    file = models.FileField(verbose_name=_("Файл с ответом"), upload_to='homework_submissions/')

    class Meta:
        verbose_name = _("Файл домашнего задания")
        verbose_name_plural = _("Файлы домашних заданий")

    def __str__(self):
        return f"Файл для задания: {self.homework.session.title}"


class FinalModuleSession(BaseFinalSession):
    module = models.ForeignKey(
        Module,
        verbose_name=_("Модуль"),
        on_delete=models.CASCADE,
        related_name='final_sessions'
    )

    class Meta:
        verbose_name = _("Финальное занятие модуля")
        verbose_name_plural = _("Финальные занятия модулей")

    def __str__(self):
        return self.title


class FinalCourseSession(BaseFinalSession):
    course = models.ForeignKey(
        Course,
        verbose_name=_("Курс"),
        on_delete=models.CASCADE,
        related_name='final_sessions'
    )

    class Meta:
        verbose_name = _("Финальное занятие курса")
        verbose_name_plural = _("Финальные занятия курсов")

    def __str__(self):
        return self.title


class FinalSessionResponse(models.Model):
    final_module_session = models.ForeignKey(
        FinalModuleSession,
        verbose_name=_("Финальное занятие модуля"),
        on_delete=models.CASCADE,
        related_name='responses',
        null=True,
        blank=True  # Позволяет пустое значение, если это задание курса
    )
    final_course_session = models.ForeignKey(
        FinalCourseSession,
        verbose_name=_("Финальное занятие курса"),
        on_delete=models.CASCADE,
        related_name='responses',
        null=True,
        blank=True  # Позволяет пустое значение, если это задание модуля
    )
    student = models.ForeignKey(
        UserProfile,
        verbose_name=_("Студент"),
        on_delete=models.CASCADE,
        related_name='final_responses'
    )
    comment = models.TextField(verbose_name=_("Комментарий студента"), blank=True, null=True)
    feedback = models.TextField(verbose_name=_("Комментарии преподавателя"), blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата отправки"))

    class Meta:
        verbose_name = _("Ответ на финальное занятие")
        verbose_name_plural = _("Ответы на финальные занятия")

    def __str__(self):
        if self.final_module_session:
            return f"Ответ студента {self.student} на занятие {self.final_module_session.title}"
        if self.final_course_session:
            return f"Ответ студента {self.student} на занятие {self.final_course_session.title}"
        return "Ответ студента без привязки к занятию"

education_system/mainapp/forms.py
from django import forms
from .models import Homework, FinalSessionResponse, TestQuestion


class HomeworkForm(forms.ModelForm):
    class Meta:
        model = Homework
        fields = ['answer']  # Без файла здесь

    def __init__(self, *args, **kwargs):
        super(HomeworkForm, self).__init__(*args, **kwargs)
        self.fields['answer'].label = "Ответ"


class FinalSessionResponseForm(forms.ModelForm):
    class Meta:
        model = FinalSessionResponse
        fields = ['comment']  # Без файла здесь

    def __init__(self, *args, **kwargs):
        super(FinalSessionResponseForm, self).__init__(*args, **kwargs)
        self.fields['comment'].label = "Ответ"


class TestResponseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        test = kwargs.pop('test')
        super().__init__(*args, **kwargs)

        for question in test.questions.all():
            if question.question_type == TestQuestion.SINGLE_CHOICE:
                self.fields[f'question_{question.id}'] = forms.ChoiceField(
                    label=question.question_text,
                    choices=[(choice.id, choice.choice_text) for choice in question.choices.all()],
                    widget=forms.RadioSelect
                )
            elif question.question_type == TestQuestion.MULTIPLE_CHOICE:
                self.fields[f'question_{question.id}'] = forms.MultipleChoiceField(
                    label=question.question_text,
                    choices=[(choice.id, choice.choice_text) for choice in question.choices.all()],
                    widget=forms.CheckboxSelectMultiple
                )
            elif question.question_type == TestQuestion.TEXT_ANSWER:
                # Поле для текстового ответа
                self.fields[f'question_{question.id}'] = forms.CharField(
                    label=question.question_text,
                    widget=forms.Textarea(attrs={'rows': 3}),  # Добавление атрибута для текстовой области
                    required=False  # Текстовый ответ может быть необязательным
                )

    def add_widget_classes(self):
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.Textarea):
                field.widget.attrs.update({'class': 'form-control textarea-custom'})
            else:
                field.widget.attrs.update({'class': 'form-control'})

education_system/mainapp/templates/mainapp/courses/course_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="course__detail">
    <div class="course__detail__section">
        <img src="{{ course.images.url }}" alt="Изображение курса" class="course__detail__image">
        <div>
            <h1>{{ course.name }}</h1>
            <p>{{ course.desc }}</p>
            {% if user in course.students.all %}
                <a href="{% url 'modules:view_module' course.slug %}" class="button">Перейти к модулям</a>
            {% else %}
            {% endif %}
        </div>
    </div>
	<div class="course__detail__programm">
		<h1 class="course__detail__programm__title">
			Программа курса
		</h1>
		{% for module in course.module_course.all %}
		<div class="course__detail__module__section">
			<h2 class="course__detail__module__name">
				{{ module.name }}
				<a type="button" class="course__detail__module__toggle">+</a>
			</h2>
			<p class="course__detail__module__desc course__detail__module__desc__hidden">
				{{ module.desc }}
			</p>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

education_system/mainapp/templates/mainapp/courses/course_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="course">
    {% if purchased_courses %}
    <div class="course__users">
        <h1 class="course__section__title">Мои курсы</h1>
        <div class="course__list">
            {% for user_course in purchased_courses %}
            <div class="course__items">
                <div class="course__items__images">
                    <img src="{{ user_course.images.url }}" alt="Изображение курса" class="course__items__images">
                </div>
                <h2 class="course__items__name">{{ user_course.name }}</h2>
                <p class="course__items__complexity">{{ user_course.get_complexity_display }}</p>
                <a href="{% url 'main:purchased_course_detail' user_course.slug %}" class="course__items__link">Перейти к
                    курсу</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

<div class="course__section">
    <h1 class="course__section__title">Все курсы</h1>
    <div class="course__list">
        {% for course in available_courses %}
        <div class="course__items">
            <div class="course__items__images">
                <img src="{{ course.images.url }}" alt="Изображение курса" class="course__items__images">
            </div>
            <h2 class="course__items__name">{{ course.name }}</h2>
            <p class="course__items__complexity">{{ course.get_complexity_display }}</p>
            <a href="{% url 'main:course_detail' course.slug %}" class="course__items__link">Подробнее</a>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

education_system/mainapp/templates/mainapp/courses/final_session.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
{% if final_session.task_condition %}
<div class="course__homework">
    <div>
        <h1 class="lesson__title">
            Задание
        </h1>
    </div>
    <div>
        <p class="lesson__work">
            {{final_session.task_condition|linenumbers|linebreaks}}
        </p>
    </div>
</div>
{% endif %}
{% if final_responses.exists %}
<div class="course__homework">
    <div>
        <h1 class="lesson__title">
            Ваши ответы
        </h1>
    </div>
    {% for item in final_responses %}
    {% if item.comment or item.files.count %}
    <div class="course__homework__answer">
        <div class="answer__block__text">
            <h4 style="float: right">
                Комментарий студента
            </h4>
            <p class="home__work__answer__text">
                {% if item.comment %}
                {{ item.comment }}
                {% else %}
                Комментарий отсутствует
                {% endif %}
            </p>
        </div>

        <div class="answer__block__file">
            {% if item.files.count > 0 %}
            <p>Ваши файлы:</p>
            <a href="?download_response_id={{ item.id }}" class="button">Скачать</a>
            {% else %}
            {% endif %}
        </div>
    </div>

    {% if item.feedback %}
    <div class="course__homework__teacher">
        <div class="answer__block__text">
            <h4 style="float: right">
                Комментарий преподавателя
            </h4>
            <p class="home__work__answer__text">
                {{ item.feedback }}
            </p>
        </div>
    </div>
    {% endif %}
    {% else %}
    {% endif %}
    {% endfor %}
</div>
{% else %}
<div class="course__homework">
    <div>
        <h1 class="lesson__title">
            Ваши ответы
        </h1>
    </div>
    <p>Задания еще не сданы.</p>
</div>
{% endif %}

<form method="post" enctype="multipart/form-data" class="course__homework__form">
    {% csrf_token %}
    <div class="form__block__text">
        <textarea name="comment" maxlength="256" class="home__work__form__text" id="id_answer"
                  placeholder="Ваш комментарий (необязательно)"></textarea>
        <div class="home__work__form__div__button">
            <button type="submit" class="home__work__form__button">Отправить</button>
        </div>
    </div>
    <div class="form__block__file">
        <label for="id_files" class="home__work__form__label">Выберите файлы</label>
        <input type="file" name="files" class="home__work__form__file" multiple id="id_files">
    </div>
</form>

{% endblock %}

education_system/mainapp/templates/mainapp/courses/lesson_teacher.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% load static %}
<div class="lesson__teacher">
    <div class="lesson__teacher__items">
        <div>
            <p>№</p>
        </div>
        <div>
            <p>id</p>
        </div>
        <div>
            <p>Email</p>
        </div>
        <div>
            <p>
                Файл
            </p>
        </div>
        <div>
            <p>
                Комментарий
            </p>
        </div>
        <div>

        </div>
    </div>
    {% for item in final_response %}
    <div class="lesson__teacher__items">
        <div>
            <p class="lesson__teacher__items__text"></p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.student.id}}</p>
        </div>
        <div>
            <p class="lesson__teacher__items__text">{{item.student.email}}</p>
        </div>
        <div>
            <a href="{{ item.file.url }}" target="_blank">Скачать</a>
        </div>
        <div>
            <p class="lesson__teacher__items__text">
                {{item.comment_student}}
            </p>
        </div>
        <div>
            {% if item.comment_teacher %}
            <p class="lesson__teacher__items__text">
                {{item.comment_teacher}}
            </p>
            {% else %}
            <a href="">Оставить комментарий</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

education_system/mainapp/templates/mainapp/courses/module_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="module-detail">
    <h2>Занятия</h2>
    {% for session in sessions %}
    {% if session.is_active %}
    <a class="course__module__item" href="{% url 'main:session'  module.course.slug module.id session.id %}">
        {{ session.title }}
        <img class="course__module__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
    </a>
    {% else %}
    <span class="course__module__item disabled">
            {{ session.title }}
            <img class="course__module__item__img" src="{% static 'img/course/module/close.png' %}" alt="Закрыто">
        </span>
    {% endif %}
    {% endfor %}

    <h2>Финальные задания</h2>
    {% for final_assignment in final_assignments %}
    {% if final_assignment.is_active %}
    <a class="course__module__item"
       href="{% url 'main:final_module_session' module.course.slug module.id final_assignment.id %}">
        {{ final_assignment.title }}
        <img class="course__module__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
    </a>
    {% else %}
    <span class="course__module__item disabled">
            {{ final_assignment.title }}
            <img class="course__module__item__img" src="{% static 'img/course/module/close.png' %}" alt="Закрыто">
        </span>
    {% endif %}
    {% endfor %}

    <h2>Тестирование</h2>
    {% for test in tests %}
    {% if test.is_active %}
    <a class="course__module__item" href="{% url 'main:take_test_module' module.course.slug module.id test.id %}">
        {{ test.title }}
        <img class="course__module__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
    </a>
    {% else %}
    <span class="course__module__item disabled">
        {{ test.title }}
        <img class="course__module__item__img" src="{% static 'img/course/module/close.png' %}" alt="Закрыто">
    </span>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

education_system/mainapp/templates/mainapp/courses/purchased_course_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="course__purchased">
    {% for module in modules %}
        {% if user in module.completed_by.all %}
            <a class="course__purchased__item" href="{% url 'main:module_detail'  module.course.slug module.id %}">
                {{ module.name }}
                <img class="course__purchased__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
            </a>
        {% else %}
            <span class="course__purchased__item disabled">
                {{ module.name }}
                <img class="course__purchased__item__img" src="{% static 'img/course/module/close.png' %}" alt="Закрыто">
            </span>
        {% endif %}
    {% endfor %}

    {% for assignment in final_course_assignments %}
        {% if user in assignment.course.students.all %}
            <a class="course__purchased__item" href="{% url 'main:final_course_session' course.slug assignment.id %}">
                {{ assignment.title }}
                <img class="course__purchased__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
            </a>
        {% else %}
            <span class="course__purchased__item disabled">
                {{ assignment.title }}
                <img class="course__purchased__item__img" src="{% static 'img/course/module/close.png' %}" alt="Закрыто">
            </span>
        {% endif %}
    {% endfor %}

    {% for test in tests %}
        {% if user in test.course.students.all %}
            <a class="course__purchased__item" href="{% url 'main:take_test_course' course.slug test.id %}">
                {{ test.title }}
                <img class="course__purchased__item__img" src="{% static 'img/course/module/open.png' %}" alt="Открыто">
            </a>
        {% else %}
            <span class="course__purchased__item disabled">
                {{ test.title }}
                <img class="course__purchased__item__img" src="{% static 'img/course/module/close.png' %}" alt="Закрыто">
            </span>
        {% endif %}
    {% endfor %}
</div>

{% endblock %}

education_system/mainapp/templates/mainapp/courses/session.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="course__lesson">
    <div>
        <h1 class="lesson__title">
            Тема занятия: {{ session.title }}
        </h1>
    </div>
    <div class="lesson__block">
        <a href="{{ session.webinar_link }}" target="_blank" class="lesson__block__item">
            Вебинар
        </a>
        {% if session.presentation %}
        <a href="{{ session.presentation.url }}" target="_blank" class="lesson__block__item">
            Презентация
        </a>
        {% endif %}
        {% if session.annotation %}
        <a href="{{ session.annotation.url }}" target="_blank" class="lesson__block__item">
            Аннотация
        </a>
        {% endif %}
    </div>
</div>
{% if session.homework_condition %}
<div class="course__homework">
    <div>
        <h1 class="lesson__title">
            Домашняя работа
        </h1>
    </div>
    <div>
        <p class="lesson__work">
            {{session.homework_condition|linenumbers|linebreaks}}
        </p>
    </div>
</div>
{% endif %}
{% if home_work.exists %}
<div class="course__homework">
    <div>
        <h1 class="lesson__title">
            Ваши ответы
        </h1>
    </div>
    {% for item in home_work %}
    {% if item.answer or item.files.count %}
    <div class="course__homework__answer">
        <div class="answer__block__text">
            <h4 style="float: right">
                Комментарий студента
            </h4>
            <p class="home__work__answer__text">
                {% if item.answer %}
                {{ item.answer }}
                {% else %}
                Комментарий отсутствует
                {% endif %}
            </p>
        </div>

        <div class="answer__block__file">
            {% if item.files.count > 0 %}
            <p>Ваши файлы:</p>
            <a href="?download_homework_id={{ item.id }}" class="button">Скачать</a>
            {% else %}
            {% endif %}
        </div>
    </div>

    {% if item.feedback %}
    <div class="course__homework__teacher">
        <div class="answer__block__text">
            <h4 style="float: right">
                Комментарий преподавателя
            </h4>
            <p class="home__work__answer__text">
                {{ item.feedback }}
            </p>
        </div>
    </div>
    {% endif %}
    {% else %}
    {% endif %}
    {% endfor %}
</div>
{% else %}
<div class="course__homework">
    <div>
        <h1 class="lesson__title">
            Домашняя работа
        </h1>
    </div>
    <p>Домашние задания еще не сданы.</p>
</div>
{% endif %}

<form method="post" enctype="multipart/form-data" class="course__homework__form">
    {% csrf_token %}
    <div class="form__block__text">
        <textarea name="answer" maxlength="256" class="home__work__form__text" id="id_answer"
                  placeholder="Ваш комментарий (необязательно)"></textarea>
        <div class="home__work__form__div__button">
            <button type="submit" class="home__work__form__button">Отправить</button>
        </div>
    </div>
    <div class="form__block__file">
        <label for="id_files" class="home__work__form__label">Выберите файлы</label>
        <input type="file" name="files" class="home__work__form__file" multiple id="id_files">
    </div>
</form>

{% endblock %}